export default {
    trueCity : [
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true]]
    ,
    clearedCity : [
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]]
    ,
    predefinedCity : [
        [false, true,  false, false, true,  true,  false, false, true,  true,  false, false, true,  false, false, true,  true,  false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, true,  false, false, false, false, false, false, false, false, false, false, true, ],
        [true,  true,  false, false, true,  true,  false, false, true,  true,  false, false, true,  false, false, false, true,  false, false, false, ],
        [false, true,  false, false, true,  true,  false, false, true,  true,  false, false, true,  false, false, true,  true,  false, false, true, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, true,  false, false, false, false, false, false, false, false, false, false, false, ],
        [true,  true,  false, false, true,  true,  false, false, true,  true,  false, false, true,  false, false, false, true,  false, false, false, ]]
    ,
    predefinedCityNextTurn : [
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, true,  true,  false, false, false, false, false, false, false, false, false, false, ],
        [true,  true,  false, false, true,  true,  false, true,  false, false, false, false, false, false, false, true,  true,  false, false, false, ],
        [true,  true,  false, false, true,  true,  false, false, true,  true,  false, false, false, false, false, true,  true,  false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, true,  true,  false, false, false, false, false, false, false, false, false, false, ],
        [false, false, false, false, false, false, false, false, true,  true,  false, false, false, false, false, false, false, false, false, false, ]]
    ,    
    undefinedCity : [
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]] 
}